# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_jackknife_engine <- function(X, y, n_blocks, overlap_prop, scale) {
    .Call(`_fastLDSC_run_jackknife_engine`, X, y, n_blocks, overlap_prop, scale)
}

